import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import SemSelector from "./components/SemSelector";
import Script from "next/script";
import { useEffect, useState } from "react";
import NewSemModal from "./components/NewSemModal";
import { collection, doc, getDoc, getDocs } from "firebase/firestore";
import { db } from "@/firebase";
import { Timeslot, initTimeslots } from "./api/constants";
import Scheduler from "./components/Scheduler";

export default function Home() {
  const [show, setShow] = useState(false);
  const [semList, setSemList] = useState<string[]>([]);
  const [timeslots, setTimeslots] = useState<Timeslot>(initTimeslots);
  const [semester, setSemester] = useState("");

  const fetchSems = async () => {
    const sems = await getDocs(collection(db, "semesters"));
    try {
      setSemList([]);
      if (sems.docs.length > 0) setSemester(sems.docs[0].id);
      sems.docs.map((document) => {
        if (semList.indexOf(document.id) === -1) {
          setSemList((prevSemList) => [...prevSemList, document.id]);
        }
      });
    } catch (error) {
      console.log(error);
    }
  };

  const fetchTimeslots = async () => {
    let ts: Timeslot = initTimeslots;
    try {
      if (semester !== "")
        ts =
          ((await getDoc(doc(db, "semesters", semester))).data() as Timeslot) ||
          initTimeslots;
    } catch (error) {
      console.log(error);
    }
    setTimeslots(ts);
  };

  useEffect(() => {
    fetchSems();
  }, []);

  useEffect(() => {
    fetchTimeslots();
  }, [semester]);

  return (
    <>
      <Head>
        <title>Schedulr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen">
        <Script src="https://cdn.tailwindcss.com"></Script>
        <div className="h-full">
          <nav className="w-full h-11 px-5 flex bg-red-600 justify-between">
            <div className="font-semibold mx-3 flex flex-col justify-center text-white">
              SCHEDULER
            </div>

            <div className="nav-end flex">
              <SemSelector
                setShow={setShow}
                semList={semList}
                semester={semester}
                setSemester={setSemester}
              />
            </div>
          </nav>
          <NewSemModal
            show={show ?? false}
            setShow={setShow}
            setSemList={setSemList}
            semList={semList}
          />

          <Scheduler timeslots={timeslots} />
        </div>
      </main>
    </>
  );
}
