import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { RawData, Semester, SemesterActions } from "../api/interfaces";
import { Dispatch, useEffect, useReducer, useState } from "react";
import { initSemester } from "../api/constants";
import { collection, doc, getDoc, getDocs } from "firebase/firestore";
import { db } from "@/firebase";
import { SemesterContext } from "@/context/semContext";
import { SemListContext } from "@/context/semListContext";
import SemesterSection from "@/components/sections/SemesterSection";
import semReducer from "@/reducer/semReducer";
import SchedulesSection from "@/components/sections/SchedulesSection";
import ClassSection from "@/components/sections/ClassSection";
import { library } from "@fortawesome/fontawesome-svg-core";
import { fas } from "@fortawesome/free-solid-svg-icons";

library.add(fas);

export default function Home() {
  const [sem, semDispatch] = useReducer(semReducer, initSemester);
  const [semList, setSemList] = useState<Semester[]>([]);

  const fetchSems = async () => {
    const sems = await getDocs(collection(db, "semesters"));
    try {
      setSemList([]);
      if (sems.docs.length > 0) {
        const toAdd = sems.docs[0].data() as RawData;
        semDispatch({
          type: "set",
          payload: {
            semester: {
              semesterId: sems.docs[0].id,
              rooms: toAdd.rooms,
              classes: toAdd.classes,
            },
          },
        });
      }
      sems.docs.map((document) => {
        if (
          !semList.some((e) => {
            return document.id === e.semesterId;
          })
        ) {
          const toAdd = document.data() as RawData;
          setSemList((prevSemList) => [
            ...prevSemList,
            {
              semesterId: document.id,
              rooms: toAdd.rooms,
              classes: toAdd.classes,
            },
          ]);
        }
      });
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    fetchSems();
  }, []);

  return (
    <>
      <Head>
        <title>Schedulr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com" async />
      </Head>

      <SemListContext.Provider
        value={{
          list: semList,
          setList: setSemList,
        }}
      >
        <SemesterContext.Provider
          value={{
            state: sem,
            dispatch: semDispatch,
          }}
        >
          <main className="h-screen bg-white">
            <div className="h-full">
              <nav className="w-full px-5 flex bg-red-600 justify-between">
                <div className="font-semibold my-3 mx-3 flex flex-col justify-center text-white">
                  SCHEDULER
                </div>

                <div className="nav-end flex">
                  <SemesterSection />
                </div>
              </nav>

              <div className="flex h-full ">
                <SchedulesSection />
                <ClassSection />
              </div>
            </div>
          </main>
        </SemesterContext.Provider>
      </SemListContext.Provider>
    </>
  );
}
