import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import SemSelector from "./components/SemSelector";
import Script from "next/script";
import { useState } from "react";
import NewSemModal from "./components/NewSemModal";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [show, setShow] = useState(false);
  const [semList, setSemList] = useState([]);
  const [semester, setSemester] = useState("");

  return (
    <>
      <Head>
        <title>Schedulr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Script src="https://cdn.tailwindcss.com"></Script>
        <nav className="w-full h-11 px-5 flex bg-red-600 justify-between">
          <ul className="flex">
            <li className="font-semibold mx-3 flex flex-col justify-center">
              SCHEDULER
            </li>
          </ul>

          <div className="nav-end flex my-auto">
            <SemSelector
              setShow={setShow}
              semList={semList}
              semester={semester}
              setSemester={setSemester}
            />
          </div>
        </nav>

        <NewSemModal show={show ?? false} setShow={setShow} />
      </main>
    </>
  );
}
